# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  run:
    desc: run app
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  reset:
    desc: reset app / delete db
    cmds:
      - rm -rf db
    silent: true
